apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: rabbitmq-operator
resources:
  - https://github.com/rabbitmq/cluster-operator/releases/download/v2.11.0/cluster-operator.yml
  # - repository.yaml
  # - release.yaml
