---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alpine
  namespace: default
  labels:
    app: debug-alpine
spec:
  selector:
    matchLabels:
      app: debug-alpine
  template:
    metadata:
      labels:
        app: debug-alpine
    spec:
      containers:
      - image: alpine:3.15.0
        name: alpine-debug
        command:
          - /bin/sh
          - "-c"
        args:
          - apk update;
            apk add curl;
            apk add nmap;
            sleep 60m
