---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: psql
  namespace: flux-system
spec:
  interval: 2m0s
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/psql
  prune: true
  wait: true
  timeout: 2m0s
  suspend: true
