apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  releaseName: postgres-operator
  chart:
    spec:
      chart: postgres-operator
      sourceRef:
        kind: HelmRepository
        name: psql
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://psql.com/psql-org/charts/psql/-/blob/master/values.yaml
  # values:
  #   global.edition=ce
